---
grails:
    profile: web
    codegen:
        defaultPackage: m3oh1
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

    plugins:
        twitterbootstrap:
            fixtaglib: true
    exceptionresolver.params.exclude:
        - 'password'
    plugin:
        springsecurity:
            userLookup:
                userDomainClassName: 'io.threeohone.security.User'
                authorityJoinClassName: 'io.threeohone.security.UserRole'
                authority.className: 'io.threeohone.security.Role'
            userBasicAuth: true
            basic.realmName: '3oh1'
            passsword:
                algorithm: 'SHA-256'
                hash.iterations: 1
            logout:
                postOnly: false
            controllerAnnotations.staticRules:
                - pattern: '/docs/**'
                  access: ['permitAll']
                - pattern: '/dbconsole/**'
                  access: ['permitAll']
                - pattern: '/console/**'
                  access: ['permitAll']
                - pattern: '/'
                  access: ['permitAll']
                - pattern: '/index'
                  access: ['permitAll']
                - pattern: '/index.gsp'
                  access: ['permitAll']
                - pattern: '/assets/**'
                  access: ['permitAll']
                - pattern: '/**/js/**'
                  access: ['permitAll']
                - pattern: '/**/css/**'
                  access: ['permitAll']
                - pattern: '/**/images/**'
                  access: ['permitAll']
                - pattern: '/**/favicon.ico'
                  access: ['permitAll']
#            controllerAnnotations.staticRules: [
#                    [pattern: '/docs/**',           access: ['permitAll']],
#                    [pattern: '/dbconsole/**',      access: ['permitAll']],
#                    [pattern: '/console/**',        access: ['permitAll']],
#                    [pattern: '/',                  access: ['permitAll']],
#                    [pattern: '/index',             access: ['permitAll']],
#                    [pattern: '/index.gsp',         access: ['permitAll']],
#                    [pattern: '/assets/**',         access: ['permitAll']],
#                    [pattern: '/**/js/**',          access: ['permitAll']],
#                    [pattern: '/**/css/**',         access: ['permitAll']],
#                    [pattern: '/**/images/**',      access: ['permitAll']],
#                    [pattern: '/**/favicon.ico',    access: ['permitAll']]
#                ]
            filterChain.chainMap:
                - pattern: '/api/**'
                  filters: 'JOINED_FILTERS,-exceptionTranslationFilter'
                - pattern: '/**'
                  filters: 'JOINED_FILTERS,-basicAuthenticationFilter,-basicExceptionTranslationFilter'
        fields.disableLookupCache: true
        geoip.data.cache: 0

endpoints:
    jmx:
        unique-names: true

---
hibernate:
    format_sql: true
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        grails.loggin.jul.usebridge: true
        grails.plugin.geoip.data.path: 'web-app/data/maxmind/GeoLiteCity.dat'
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
